version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - /Users/senyuva/workspace/psychoacoustics-web/:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_mysql_username'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - "8080:80"
    depends_on:
      - mysql
